### ISSUE TITLE
MagicMirror won't start 

### ISSUE THREAD

**Issue by pimagical** [CFenner/MMM-AirQuality#4]
When i add this module the MagicMirror won't start and the screen stays black.

Tried this module with the default example location "Beijing".

**Comment by CFenner** [comment]
I didn't update my mirror for some time. I'll have a look at it.

**Comment by CFenner** [comment]
Can you give any error message? What does your browser say if you open the console?

**Comment by pimagical** [comment]
I followed this wiki for installing the modules: https://github.com/MichMich/MagicMirror/wiki/MagicMirror%C2%B2-Modules
And used this example: git clone https://github.com/author/module-name

Sorry i didn't know the folder should be renamed like "airquality" as you described.
It is working nicely, thank you anyway

**Comment by CFenner** [comment]
Ah ok, perfect :)
