### ISSUE TITLE
module stuck at loading after update

### ISSUE THREAD

**Issue by briodan** [CFenner/MMM-AirQuality#47]
updated to the latest version of both MagicMirror and this module and the module no longer loads.

reverted back to the prior versions and it loaded successfully.

did a fresh install of both MagicMirror and MMM-AirQuality and still does not load.

**Comment by CFenner** [comment]
Sorry to hear that. Any logs from the Browser or the Mirror itself?

**Comment by briodan** [comment]
never mind, forgot to do npm install and a restart after the git pull for the module, up and running now.

**Comment by CFenner** [comment]
~~Ah, but I also missed to mention that in the docs. 🤦~~
There are no productive dependencies. So must be solely the restart.
