### ISSUE TITLE
adding @number stations

### ISSUE THREAD

**Issue by briodan** [CFenner/MMM-AirQuality#50]
Hi wondering how i would go about adding a station that used an @number in the URL, for example:

https://aqicn.org/station/@360085/

**Comment by CFenner** [comment]
I guess you tried simply using that as `location` already?

**Comment by briodan** [comment]
yes I did, also tried a few variations of the URL that is shown lower on the page

https://aqicn.org/station/@360085/#/s:360085/n:barriere-spruce-crescent-canada

with no luck

**Comment by CFenner** [comment]
Ah, nice, it's listed directly on the station page, just search for API: https://aqicn.org/station/@360085/

Just replace the `@` with a `A`.
