### ISSUE TITLE
lang: 'cs' doesn't work for me

### ISSUE THREAD

**Issue by zdeneksofr** [CFenner/MMM-AirQuality#6]
Hi
this is my config.js
```
		{
			module: 'airquality',
			position: 'bottom_left', // the location where the module should be displayed
			config: {
				lang: 'cs', 
			        location: 'czechrepublic/liberecky/liberec-rochlice' // aqicn.org
				}
		},
```
but still have in in english. Do I need to add definitions to traslations/cs.json ? If yes, where is possible to get full list of possibilities?

btw, is there way, how to make the modules smaller and hwo to use colours based on condition? 

thanks, Zdeněk

**Comment by CFenner** [comment]
Like mentioned in [known issues](https://github.com/CFenner/MagicMirror-AirQuality-Module#known-issues) not all languages are supported.

But maybe you can provide [translation](http://aqicn.org/faq/2015-07-28/air-quality-widget-new-improved-feed/) for the service.

Works for DE or FR:
<img width="163" alt="bildschirmfoto 2017-05-14 um 10 03 50" src="https://cloud.githubusercontent.com/assets/9592452/26032171/ddd0d352-388c-11e7-9d7d-916ca2bec4e6.png">
<img width="178" alt="bildschirmfoto 2017-05-14 um 10 03 04" src="https://cloud.githubusercontent.com/assets/9592452/26032170/ddcf4406-388c-11e7-8b75-43b0f2a89b73.png">

**Comment by zdeneksofr** [comment]
great idea. I'be no problem to try to make tramslation, if I'll have a full list of all possible values. Do you have it?

**Comment by CFenner** [comment]
No, I fetch the information from an external service: http://aqicn.org/translate/#v

Seems that czech is not supported.

**Comment by CFenner** [comment]
One idea is, to query in english all the time and do the translation in the module itself.

**Comment by zdeneksofr** [comment]
@CFenner I asked 

>  http://aqicn.org/translate/#v

there, so we will see

**Comment by rubenix** [comment]
Seems that Language Translation service has been moved to: http://waqi.info/translate/#/

I see Catalan language its supported (ca) but not working in the module (I thing you should change something in the code to make it working, right?)

thanks
